export enum ProviderPlatform {
  GEMINI_OAUTH = 'GEMINI_OAUTH',
  GEMINI_APIKEY = 'GEMINI_APIKEY',
  CLAUDE_OAUTH = 'CLAUDE_OAUTH',
  CLAUDE_APIKEY = 'CLAUDE_APIKEY',
  OPENAI_OAUTH = 'OPENAI_OAUTH',
  OPENAI_APIKEY = 'OPENAI_APIKEY',

  // Antigravity 平台（统一代理，支持 Gemini 和 Claude 模型）
  ANTIGRAVITY = 'ANTIGRAVITY'
}
